= GraphQL Forum

== Features

=== Basic Functionality

* [ ] Serves a frontend
* [x] Backend with tracing
* [x] List topics
* [x] Topic by id
* [x] Create topic
* [x] Create post
* [x] Delete topic
* [x] Delete post

=== Authentication

* [x] Sessions
* [x] Password authentication
* [x] Login via username/password
* [x] Registration
* [x] Change password

=== Authorization

* [x] Only admins/author can see deleted topics and posts
* [x] Regular users can see their own posts/topics and any public posts/topics
* [x] Regular users can only delete their own posts
* [x] Admin can delete every post

=== Anti-features

* [x] Terrible error messages
* [x] `panic!`, `unwrap`, and `expect` everywhere
* [x] Barely any defenses
* [x] Spaghetti code scattered around like crazy
* [x] No documentation

== Design Choices

=== N+1

N+1 is not purposefully avoided.
Joins are used to ensure correctness and access control, but not for performance (yet).
See: https://www.sqlite.org/np1queryprob.html.

=== Access Control

Metadata consistency and access control are ensured on SQL queries instead of at application level.
Access control comes in form of 4 views: `topic_permissions`, `topic_public`, `post_permissions`, and `post_public`.

=== Invariants

* Posts are never deleted from database.
* Post number is never changed.
* Post metadata is always accessible, but contents can only be viewed as permitted.

These invariants are enforced by the SQL query used to access posts.

== Experience Report

WARNING: DO NOT IMPLEMENT PASSWORD AUTHENTICATION AND SESSIONS YOURSELF!

=== The Good

* Great performance without even trying
* `async-graphql` object definition is relatively easy to use... once I got the basics
* The compiler is very good at catching mistakes, if I am actually using types properly

=== The Bad

* Really, we are manually doing monadic stack here by using `Context<'_'>`...
* `async-graphql` doesn't work very well with Axum middleware
** Cannot use `CookieJar` because we cannot return extra arguments
*** Ended up rolling my own implementation to sign cookies
** Repetition in binding middleware (in Axum and `async-graphql`)
* `sqlx` generics are extremely hard to check, but I managed to use some anyways
* `sqlx` macros do not work well with SQLite, because it type checks SQLite bytecode at compile time. This has some bugs, and is an extremely slow process