DROP TRIGGER tr_posts_after_insert;
DROP TRIGGER tr_users_after_update;
DROP TRIGGER tr_topics_after_update;
DROP TRIGGER tr_posts_after_update;
DROP VIEW post_metadata;
DROP TABLE active_sessions;
DROP TABLE posts;
DROP TABLE topics;
DROP TABLE users;